classDiagram
class GameController{
    +create()
}

class Player{
    +create()
}

class Defender{
    +spawn()
}

class Field{
    +load()
}

class Score{
    +reset()
}

GameController --> Player
GameController --> Defender
GameController --> Field
GameController --> Score